{application,floki,
             [{registered,[]},
              {description,"Floki is a simple HTML parser that enables search for nodes using CSS selectors."},
              {vsn,"0.8.1"},
              {modules,['Elixir.Floki','Elixir.Floki.AttributeSelector',
                        'Elixir.Floki.Combinator','Elixir.Floki.DeepText',
                        'Elixir.Floki.FilterOut','Elixir.Floki.Finder',
                        'Elixir.Floki.FlatText','Elixir.Floki.Parser',
                        'Elixir.Floki.Selector','Elixir.Floki.SelectorParser',
                        'Elixir.Floki.SelectorTokenizer',
                        floki_selector_lexer]},
              {applications,[kernel,stdlib,elixir,mochiweb_html]}]}.